module.exports = {
	content: [
		'./pages/**/*.{js,ts,jsx,tsx}',
		'./components/**/*.{js,ts,jsx,tsx}',
		'./sections/**/*.{js,ts,jsx,tsx}',
		'./public/**/*.{html, js,ts,jsx,tsx}',
	],
	theme: {
		screens: {
			xs: '320px',
			sm: '640px',
			md: '768px',
			lg: '1024px',
			xl: '1280px',
			'2xl': '1536px',
		},
		extend: {
			colors: {
				primary: {
					DEFAULT: 'hsl(var(--primary-base))',
					dark: 'hsl(var(--primary-dark))',
					light: 'hsl(var(--primary-light))',
					lighter: 'hsl(var(--primary-lighter))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary-base))',
					dark: 'hsl(var(--secondary-dark))',
					light: 'hsl(var(--secondary-light))',
					lighter: 'hsl(var(--secondary-lighter))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				danger: {
					DEFAULT: 'hsl(var(--danger-base))',
					dark: 'hsl(var(--danger-dark))',
					light: 'hsl(var(--danger-light))',
					lighter: 'hsl(var(--danger-lighter))',
					foreground: 'hsl(var(--danger-foreground))',
				},
			},
			fontFamily: {
				Benne: ['Benne'],
				Besley: ['Besley'],
				Bayon: ['Bayon'],
				BarlowCondensed: ['Barlow Condensed'],
				LexendDeca: ['Lexend Deca'],
				LexendTera: ['Lexend Tera'],
				Inter: ['Inter'],
				SatoshiVariable: ['Satoshi Variable'],
				PublicSans: ['Public Sans'],
				Bevan: ['Bevan'],
				Manrope: ['Manrope'],
				NotoSans: ['Noto Sans'],
				Lora: ['Lora'],
				Montserrat: ['Montserrat'],
				Inter: ['Inter'],
				LexendDeca: ['Lexend Deca'],
				LexendTera: ['Lexend Tera'],
				Lato: ['Lato'],
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
		},
	},

	plugins: [],
};
